apiVersion: rbac.authorization.k8s.io/v1
# 此角色绑定允许 "myuser" 读取 "kube-system" 名字空间中的 Pods
kind: RoleBinding
metadata:
  name: read-pods
  namespace: kube-system
subjects:
  # 你可以指定不止一个“subject（主体）”
  - kind: User
    name: myuser # "name" 是区分大小写的
    apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" 指定与某 Role 或 ClusterRole 的绑定关系
  kind: Role # 此字段必须是 Role 或 ClusterRole
  name: pod-reader     # 此字段必须与你要绑定的 Role 或 ClusterRole 的名称匹配
  apiGroup: rbac.authorization.k8s.io
