apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31400
    - name: agent
      port: 50000
      targetPort: 50000
      nodePort: 31401
  selector:
    app: jenkins
