apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-claim
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-csi
