---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: jenkins
    name: jenkins
    namespace: jenkins
  spec:
    ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: web
    - name: agent
      port: 50000
      protocol: TCP
      targetPort: agent
    selector:
      app: jenkins
  sessionAffinity: None
  type: ClusterIP
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
