apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: jenkins
    namespace: jenkins
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
      - pods/exec
    verbs:
      - create
      - delete
      - get
      - list
      - patch
  - apiGroups:
    - ""
    resources:
      - pods/logs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - ""
    resources:
      - events
    verbs:
      - watch
  - apiGroups:
    - ""
    resources:
      - secrets
    verbs:
      - get
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
